name: Tag Check

on:
  push:
    branches: [ main ]

jobs:
  tag-check:
    runs-on: ubuntu-latest
    name: Tag Checker
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat ${{ github.event_path }}
        echo 'hello'
