name: Tag Check Tag

on:
  push:
    tags:
      - 'release-*'

jobs:
  tag-check:
    runs-on: ubuntu-latest
    name: Tag Checker
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "$GITHUB_REF"
        echo ${GITHUB_REF:10}
    - run: |
        git ls-remote --exit-code --heads origin
    - run: |
        if ! git ls-remote --exit-code --heads origin ${GITHUB_REF:10}; then
          checkoutBranch=main
        fi
        echo $checkoutBranch
